# Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

runtime: custom
env: flex
service: default
env_variables:
  FRONTEND_COUNT: '4'

resources:
  cpu: 4
  memory_gb: 6

#manual_scaling:
#  instances: 1

automatic_scaling:
  min_num_instances: 4
  max_num_instances: 8

skip_files:
- ^\.git/.*$

liveness_check:
  path: '/liveness_check'

readiness_check:
  path: '/readiness_check'
  check_interval_sec: 15
  app_start_timeout_sec: 1800
