# See https://pub.dev/packages/mono_repo for details on this file
sdk:
  - 3.5.0

stages:
  - smoke_test:
    - group:
        - format
        # dart analyze doesn't support multiple dirs. A bug?
        - analyze: --fatal-infos lib/
        - analyze: --fatal-infos test/
  - unit_test:
      # Instead of --total-shards and --shard index, we are using file-based sharding,
      # as it provided better distribution of the tests.
      # https://github.com/dart-lang/test/issues/2141
      - test: -j1 --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '0~7p'`
      - test: -j1 --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '1~7p'`
      - test: -j1 --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '2~7p'`
      - test: -j1 --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '3~7p'`
      - test: -j1 --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '4~7p'`
      - test: -j1 --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '5~7p'`
      - test: -j1 --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '6~7p'`
