# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
# To update generated code, run `dart run build_runner build`
targets:
  pub_dev:
    sources:
      - '$package$'
      - 'lib/$lib$'
      - 'lib/account/models.dart'
      - 'lib/admin/models.dart'
      - 'lib/dartdoc/models.dart'
      - 'lib/frontend/handlers/pubapi.dart'
      - 'lib/frontend/handlers/routes.dart'
      - 'lib/frontend/handlers/redirects.dart'
      - 'lib/package/models.dart'
      - 'lib/publisher/models.dart'
      - 'lib/task/models.dart'
      - 'lib/scorecard/models.dart'
      - 'lib/search/models.dart'
      - 'lib/search/search_service.dart'
      - 'lib/service/openid/openid_models.dart'
      - 'lib/service/rate_limit/models.dart'
      - 'lib/service/security_advisories/models.dart'
      - 'lib/service/topics/models.dart'
      - 'lib/shared/*.dart'
      - 'lib/tool/test_profile/models.dart'
      - 'lib/tool/utils/flutter_archive.dart'
