# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
# To update generated code, run `pub run build_runner build`
targets:
  pub_dev:
    sources:
      - 'lib/account/models.dart'
      - 'lib/dartdoc/models.dart'
      - 'lib/frontend/templates/views/**/*.dart'
      - 'lib/frontend/handlers/pubapi.dart'
      - 'lib/frontend/handlers/routes.dart'
      - 'lib/frontend/handlers/redirects.dart'
      - 'lib/history/models.dart'
      - 'lib/package/models.dart'
      - 'lib/scorecard/models.dart'
      - 'lib/search/backend.dart'
      - 'lib/search/search_service.dart'
      - 'lib/shared/*.dart'
      - 'lib/tool/test_profile/models.dart'
