# See https://github.com/dart-lang/mono_repo for details
sdk:
  - 3.5.0

stages:
  - smoke_test:
    - group:
        - format
        - analyze: --fatal-infos  .
  - build_test:
    - group:
        - command: sudo apt-get update -yq && sudo apt-get install webp
        - test: -P build-only -j 1
  - unit_test:
    - group:
      - command: sudo apt-get update -yq && sudo apt-get install webp
      - test: -P presubmit --total-shards 8 --shard-index 0
    - group:
      - command: sudo apt-get update -yq && sudo apt-get install webp
      - test: -P presubmit --total-shards 8 --shard-index 1
    - group:
      - command: sudo apt-get update -yq && sudo apt-get install webp
      - test: -P presubmit --total-shards 8 --shard-index 2
    - group:
      - command: sudo apt-get update -yq && sudo apt-get install webp
      - test: -P presubmit --total-shards 8 --shard-index 3
    - group:
      - command: sudo apt-get update -yq && sudo apt-get install webp
      - test: -P presubmit --total-shards 8 --shard-index 4
    - group:
      - command: sudo apt-get update -yq && sudo apt-get install webp
      - test: -P presubmit --total-shards 8 --shard-index 5
    - group:
      - command: sudo apt-get update -yq && sudo apt-get install webp
      - test: -P presubmit --total-shards 8 --shard-index 6
    - group:
      - command: sudo apt-get update -yq && sudo apt-get install webp
      - test: -P presubmit --total-shards 8 --shard-index 7

cache:
  directories:
    - ".dart_tool/pub-test-profile"
    - ".dart_tool/pub-search-data"
