# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
# To update generated code, run `pub run build_runner build`
targets:
  $default:
    sources:
      - '$package$'
      - 'lib/$lib$'
      - 'lib/dartdoc/dartdoc_page.dart'
      - 'lib/data/account_api.dart'
      - 'lib/data/admin_api.dart'
      - 'lib/data/advisories_api.dart'
      - 'lib/data/package_api.dart'
      - 'lib/data/page_data.dart'
      - 'lib/data/publisher_api.dart'
      - 'lib/data/task_api.dart'
      - 'lib/data/task_payload.dart'
