name: Dart CI
on:
  schedule:
    - cron: "0 0 * * 0" # runs on every Sunday
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  weekly-tests:
    # These tests are run as a sanity-check, usually involving external data or systems.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94
      - name: Install dependencies
        run: dart pub get
        working-directory: app
      - name: Run test
        run: dart test -P sanity -t sanity
        working-directory: app
